spring:
  application:
    name: order-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/restaurant}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

jwt:
  secret: "dGhpcyBpcyBhIHZlcnkgbG9uZyBzZWNyZXQga2V5IGZvciBqd3Qgc2lnbmluZw=="
  expiration-ms: 86400000

storage:
  local:
    base-path: uploads
    base-url: http://localhost:8080/images
  gcs:
    bucket-name: ${GCS_BUCKET_NAME:your-bucket-name}